name: nextuse
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  gestures: ^1.0.0  
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    #Logo
    - assets/Images/nextuse_logo/large_logo.png
    
    #Avatars
    - assets/Images/Onboarding/Onboarding 1.png
    - assets/Images/Onboarding/Onboarding 2.png
    - assets/Images/Onboarding/Onboarding 3.png
    #Platic
    - assets/Images/Inventory Items/1l PET-1.png
    - assets/Images/Inventory Items/330ml PET.png
    - assets/Images/Inventory Items/2l PET.png
    - assets/Images/Inventory Items/2l HDPE.png
    - assets/Images/Inventory Items/500ml PET.png
    #paper
    - assets/Images/Inventory Items/1l Carton.png
    - assets/Images/Egg Carton/Egg carton small no BG.png
    - assets/Images/Inventory Items/Box-1.png
    #glass
    - assets/Images/Categories/Glass.png
    - assets/Images/Categories/wine_glass.png
    #Metal
    - assets/Images/Categories/Metal.png

    #Signup logo 
    - assets/Images/Signin alternatives logos/Apple.png
    - assets/Images/Signin alternatives logos/FB.png
    - assets/Images/Signin alternatives logos/Google.png
  



